### ISSUE TITLE
Adding a hint on the history already on main screen

### ISSUE THREAD

**Issue by l00mi** [zazuko/pipelines-dashboard#1]
To have a first overview on the history of the pipelines we can add small rectangles on each Pipeline representing the last X pipeline runs.

Crude mock-up:
<img width="1377" alt="Screenshot 2021-08-25 at 11 49 32" src="https://user-images.githubusercontent.com/502518/130769470-79a033d1-f340-488b-b6e7-26d0598bfc53.png">

Background shall be white, and the boxes might be quadratic. The last run should be all to the right.

**Comment by ludovicm67** [comment]
Done and deployed!
