### ISSUE TITLE
Find a way to show the pipeline status independent of Environment

### ISSUE THREAD

**Issue by l00mi** [zazuko/pipelines-dashboard#2]
Currently we have the problem that the pipeline status overview only reflects the last run environment.

In the case that e.g. the MASTER runs before the DEV and the MASTER fails.. but DEV runs through, the pipeline shows Green which is missleading. #1 does already partly mitigate this problem, but we should think of a even clearer way to show that the last "prod" pipeline did not run.

I do not have a specific idea how to solve this. Any ideas @sandhose @ludovicm67 ?

**Comment by ludovicm67** [comment]
Regarding #1, I added the fact that when you hover a block, it will show you the name of the branch.
When you open the details of a project, you will see the status for each branch.
Is it a satisfying behavior @l00mi?

**Comment by l00mi** [comment]
Yes I think that helps a lot. Especially the blocks are a strong indicator that not all parts of the pipeline work well. It is definitely good enough for the moment.

A future improvement might be to show per Enviroment the chain of blocks. (Or simply add a column per enviroment ...)
